### ISSUE TITLE
Feature Request: Add button label and icon for open state

### ISSUE THREAD

**Issue by brianpeat** [forrestkirby/toggle-element#3]
Add  Button Label Toggled and Button Icon Toggled fields so that when the toggle is active/open, the text and icon can be different. This allows for more of an accordion type feel where the button can change from something like "View Course Description" to "Hide Course Description" along with using an open/close icon that changes when toggled.

**Comment by forrestkirby** [comment]
Hi brianpeat,

thanks for the FR. I don’t really see the need for it, though. What you describe is already possible using two toggle elements and two text elements. All four elements should have one identical class to target them, e.g. `toggle`. Then `.toggle` has to be set as value for the target attribute of both toggle elements. Additionally, the second toggle element and the second text element should have set the attribute `hidden` in the *Advanced* element settings.

It should then behave as shown in [this screencast](http://snap.ashampoo.com/uploads/2020-07-17/YRNoT6jdgFCtQd9jxK8YgHlxHm7D3DhvVUeksNnYtqMftmOLxnF7vQv67TbzXIpo.mp4).

**Comment by forrestkirby** [comment]
Closed due to inactivity
