### ISSUE TITLE
in builder when closed it hides content after it

### ISSUE THREAD

**Issue by jonathanasbell** [forrestkirby/toggle-element#7]
in Yootheme builder, when closed, it hides content after it and when toggled it reveals all content it was hiding below it

**Comment by forrestkirby** [comment]
I could not reproduce this behaviour. You have probably not set target correctly or invalid HTML markup on your site. If this is not the case, please provide the exact steps to reproduce the issue you described.

**Comment by forrestkirby** [comment]
Closed due to inactivity
