### ISSUE TITLE
hide row on load

### ISSUE THREAD

**Issue by messagedj** [forrestkirby/toggle-element#9]
First of all thanks for a great YTP add-on. I use it a lot! 

I am trying to use the Toggle to show a row on my YOOtheme Pro template. But I can't seem to get it right. I have it working but only as a toggle to close the row. I want the row to be closed on load. Is that possible?

hope you can help me, and keep up the great work!

**Comment by messagedj** [comment]
sorry, problem solved I forgot to add the hidden attribute to the row.

**Comment by forrestkirby** [comment]
Hi messagedj,

thanks for your positive feedback!

> sorry, problem solved I forgot to add the hidden attribute to the row.

Yes, exactly, you need to add the `hidden` attribute to the target element (the row, in your case). Given you already answered your own question, I’ll close this issue.

For the purpose of documentation: By default, [toggle component](https://getuikit.com/docs/toggle#component-options) will toggle the `hidden` attribute on the target, so a target which is initially shown will be hidden and a target which is initially hidden will be shown. To initially hide an element, simply add the `hidden` attribute to it.

Best regards
